In [3]:

import contractions
import unidecode
import re
import nltk
from nltk.corpus import treebank_chunk 
from nltk.chunk import RegexpParser 

text = "Hey there! 😃 I can't believe it's already 2024. Did you see John's new blog post? Check it out at https://example.com/blog! Also, email me at john.doe@example.com. He mentioned something about stemming and lemmatization—interesting stuff. BTW, I'll be attending the AI conference in N.Y.C. next month!! #Excited #AI 😊 Let's catch up soon. Cheers, John"

In [4]:
expanded_words = []    
for word in text.split():
  # using contractions.fix to expand the shortened words
  expanded_words.append(contractions.fix(word))   
   
expanded_text = ' '.join(expanded_words)
text = expanded_text


In [5]:

# display original string
print('\nOriginal String:', text)
# remove ascents
text = unidecode.unidecode(text)
 
# display new string
print('\nNew String:', text)


Original String: Hey there! 😃 I cannot believe it is already 2024. Did you see John's new blog post? Check it out at https://example.com/blog! Also, email me at john.doe@example.com. He mentioned something about stemming and lemmatization—interesting stuff. BY THE WAY, I will be attending the AI conference in N.Y.C. next month!! #Excited #AI 😊 Let us catch up soon. Cheers, John

New String: Hey there!  I cannot believe it is already 2024. Did you see John's new blog post? Check it out at https://example.com/blog! Also, email me at john.doe@example.com. He mentioned something about stemming and lemmatization--interesting stuff. BY THE WAY, I will be attending the AI conference in N.Y.C. next month!! #Excited #AI  Let us catch up soon. Cheers, John


In [6]:
print(text.lower())
print(text.upper())

hey there!  i cannot believe it is already 2024. did you see john's new blog post? check it out at https://example.com/blog! also, email me at john.doe@example.com. he mentioned something about stemming and lemmatization--interesting stuff. by the way, i will be attending the ai conference in n.y.c. next month!! #excited #ai  let us catch up soon. cheers, john
HEY THERE!  I CANNOT BELIEVE IT IS ALREADY 2024. DID YOU SEE JOHN'S NEW BLOG POST? CHECK IT OUT AT HTTPS://EXAMPLE.COM/BLOG! ALSO, EMAIL ME AT JOHN.DOE@EXAMPLE.COM. HE MENTIONED SOMETHING ABOUT STEMMING AND LEMMATIZATION--INTERESTING STUFF. BY THE WAY, I WILL BE ATTENDING THE AI CONFERENCE IN N.Y.C. NEXT MONTH!! #EXCITED #AI  LET US CATCH UP SOON. CHEERS, JOHN


In [7]:

text = re.sub(r'http\S+', '', text)
print(text)


Hey there!  I cannot believe it is already 2024. Did you see John's new blog post? Check it out at  Also, email me at john.doe@example.com. He mentioned something about stemming and lemmatization--interesting stuff. BY THE WAY, I will be attending the AI conference in N.Y.C. next month!! #Excited #AI  Let us catch up soon. Cheers, John


In [8]:
# Count vectorizer

print(text)
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
count_vectorizer = CountVectorizer(stop_words=None)
tfidf_vectorizer = TfidfVectorizer(stop_words=None)

count_vectorized = count_vectorizer.fit_transform([text])
tfidf_vectorized = tfidf_vectorizer.fit_transform([text])

import pandas as pd

count_df = pd.DataFrame(count_vectorized.toarray(), columns=count_vectorizer.get_feature_names_out())
tfidf_df = pd.DataFrame(tfidf_vectorized.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

print("CountVectorizer Results:\n", count_df)
print("\nTfidfVectorizer Results:\n", tfidf_df)

Hey there!  I cannot believe it is already 2024. Did you see John's new blog post? Check it out at  Also, email me at john.doe@example.com. He mentioned something about stemming and lemmatization--interesting stuff. BY THE WAY, I will be attending the AI conference in N.Y.C. next month!! #Excited #AI  Let us catch up soon. Cheers, John
CountVectorizer Results:
    2024  about  ai  already  also  and  at  attending  be  believe  ...  soon   
0     1      1   2        1     1    1   2          1   1        1  ...     1  \

   stemming  stuff  the  there  up  us  way  will  you  
0         1      1    2      1   1   1    1     1    1  

[1 rows x 51 columns]

TfidfVectorizer Results:
        2024     about        ai   already      also       and        at   
0  0.118678  0.118678  0.237356  0.118678  0.118678  0.118678  0.237356  \

   attending        be   believe  ...      soon  stemming     stuff       the   
0   0.118678  0.118678  0.118678  ...  0.118678  0.118678  0.118678  0.237356

In [9]:
import pandas as pd
data = pd.read_csv("textdata.csv")
data.head()

reviewText  Positive
0  This is a one of the best apps acording to a b...         1
1  This is a pretty good version of the game for ...         1
2  this is a really cool game. there are a bunch ...         1
3  This is a silly game and can be frustrating, b...         1
4  This is a terrific game on any pad. Hrs of fun...         1

In [10]:
import re 
from nltk import pos_tag
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return ' '.join(tokens)
data['cleaned_text'] = data['reviewText'].apply(preprocess_text)
count_vectorizer = CountVectorizer()
tfidf_vectorizer = TfidfVectorizer()
count_matrix = count_vectorizer.fit_transform(data['cleaned_text'])
tfidf_matrix = tfidf_vectorizer.fit_transform(data['cleaned_text'])
print("Count Vectorizer Feature Names:")
print(count_vectorizer.get_feature_names_out())
print("\nCount Vectorizer Matrix:")
print(count_matrix.toarray())

print("\nTF-IDF Vectorizer Feature Names:")
print(tfidf_vectorizer.get_feature_names_out())
print("\nTF-IDF Vectorizer Matrix:")
print(tfidf_matrix.toarray())


Count Vectorizer Feature Names:
['aa' 'aaa' 'aaaa' ... 'zzz' 'zzzz' 'zzzzz']

Count Vectorizer Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

TF-IDF Vectorizer Feature Names:
['aa' 'aaa' 'aaaa' ... 'zzz' 'zzzz' 'zzzzz']

TF-IDF Vectorizer Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from transformers import pipeline 
text1 = "I love this product! It is amazing"
text2 = "This product is terrible.I hate it"
text3 = "This product works .It is okay"

In [12]:

# text Blob
blob1 = TextBlob(text2)
blob2 = TextBlob(text2)
blob3 = TextBlob(text3)
textblob1_sentiment = blob1.sentiment
textblob2_sentiment = blob2.sentiment
textblob3_sentiment = blob3.sentiment

print(f'TextBlob 1 Sentiment :{textblob1_sentiment}')
print(f'TextBlob 2 Sentiment :{textblob2_sentiment}')
print(f'TextBlob 3 Sentiment :{textblob3_sentiment}')

TextBlob 1 Sentiment :Sentiment(polarity=-0.8, subjectivity=0.9)
TextBlob 2 Sentiment :Sentiment(polarity=-0.8, subjectivity=0.9)
TextBlob 3 Sentiment :Sentiment(polarity=0.5, subjectivity=0.5)


In [13]:
analyzer = SentimentIntensityAnalyzer()
vader_statement1 = analyzer.polarity_scores(text1)
vader_statement2 = analyzer.polarity_scores(text2)
vader_statement3 = analyzer.polarity_scores(text3)

print(f'VADER Sentiment 1 : {vader_statement1}')
print(f'VADER Sentiment 2 : {vader_statement2}')
print(f'VADER Sentiment 3 : {vader_statement3}')

VADER Sentiment 1 : {'neg': 0.0, 'neu': 0.376, 'pos': 0.624, 'compound': 0.8516}
VADER Sentiment 2 : {'neg': 0.425, 'neu': 0.575, 'pos': 0.0, 'compound': -0.5719}
VADER Sentiment 3 : {'neg': 0.0, 'neu': 0.725, 'pos': 0.275, 'compound': 0.2263}


In [15]:
sentiment_analysis = pipeline('sentiment-analysis')
transformers_sentiment1 = sentiment_analysis(text1)
transformers_sentiment2 = sentiment_analysis(text2)
transformers_sentiment3 = sentiment_analysis(text3)

print(f'Transformer Sentiment 1 : {transformers_sentiment1}')
print(f'Transformer Sentiment 2 : {transformers_sentiment2}')
print(f'Transformer Sentiment 3 : {transformers_sentiment3}')





No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /distilbert/distilbert-base-uncased-finetuned-sst-2-english/resolve/main/config.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"), '(Request ID: f80f72d1-2151-40e8-9ac2-681955d47ff5)')

In [16]:
import pandas as pd
data = pd.read_csv("textdata.csv")
data.head()

reviewText  Positive
0  This is a one of the best apps acording to a b...         1
1  This is a pretty good version of the game for ...         1
2  this is a really cool game. there are a bunch ...         1
3  This is a silly game and can be frustrating, b...         1
4  This is a terrific game on any pad. Hrs of fun...         1

In [17]:
import re 
from nltk import pos_tag
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()


def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return ' '.join(tokens)

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data['processedText'] = data['reviewText'].apply(preprocess_text)
data.tail

<bound method NDFrame.tail of                                               reviewText  Positive   
0      This is a one of the best apps acording to a b...         1  \
1      This is a pretty good version of the game for ...         1   
2      this is a really cool game. there are a bunch ...         1   
3      This is a silly game and can be frustrating, b...         1   
4      This is a terrific game on any pad. Hrs of fun...         1   
...                                                  ...       ...   
19995  this app is fricken stupid.it froze on the kin...         0   
19996  Please add me!!!!! I need neighbors! Ginger101...         1   
19997  love it!  this game. is awesome. wish it had m...         1   
19998  I love love love this app on my side of fashio...         1   
19999  This game is a rip off. Here is a list of thin...         0   

                                           processedText  
0      one best apps acording bunch people agree bomb...  
1      pret

In [19]:
analyzer = SentimentIntensityAnalyzer()


In [20]:
def get_sentiment(text):
    scores = analyzer.polarity_scores(text)
    sentiment = 1 if scores['pos'] > 0 else 0
    return sentiment

In [21]:
data['NLTK-sentiment'] = data['processedText'].apply(get_sentiment)
data.tail(10)

reviewText  Positive   
19990  you do not have to buy gems. plus, you start o...         1  \
19991  great interactive game love playing it and so ...         1   
19992  I love this app! cant get enough of it. its al...         1   
19993  If I could rate 1,000,000,000,000,000,000,000 ...         1   
19994  I hate it! I barely played it for 40 sec. befo...         0   
19995  this app is fricken stupid.it froze on the kin...         0   
19996  Please add me!!!!! I need neighbors! Ginger101...         1   
19997  love it!  this game. is awesome. wish it had m...         1   
19998  I love love love this app on my side of fashio...         1   
19999  This game is a rip off. Here is a list of thin...         0   

                                           processedText  NLTK-sentiment  
19990    buy gem plus start gem certain way get free gem               1  
19991  great interactive game love playing far bad is...               1  
19992  love app cant get enough almost like green far...               1  
19993  could rate star honestly would creator done co...               1  
19994  hate barely played sec uninstalled tap stuff l...               1  
19995  app fricken stupidit froze kindle wont allow p...               0  
19996  please add need neighbor ginger thanks bunch a...               1  
19997  love game awesome wish free stuff house didnt ...               1  
19998  love love love app side fashion story fight wo...               1  
19999  game rip list thing make betterbull first need...               1

In [22]:
from sklearn import metrics
print(metrics.confusion_matrix(data['Positive'],data['NLTK-sentiment']))
print(metrics.classification_report(data['Positive'],data['NLTK-sentiment']))





[[ 1114  3653]
 [  591 14642]]
              precision    recall  f1-score   support

           0       0.65      0.23      0.34      4767
           1       0.80      0.96      0.87     15233

    accuracy                           0.79     20000
   macro avg       0.73      0.60      0.61     20000
weighted avg       0.77      0.79      0.75     20000



In [23]:
# Splitting For train and test

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

X_train,X_test,Y_train,Y_test = train_test_split(data['processedText'],data['Positive'],test_size=0.2,random_state=42)

In [24]:
vectorizer  = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.fit_transform(X_test)

In [25]:
# logictic Regression
model_lr = LogisticRegression(max_iter=1000)
model_lr.fit(X_train_vec,Y_train)





LogisticRegression(max_iter=1000)

In [26]:
# SVM
model_svm = SVC()
model_svm.fit(X_train_vec,Y_train)


In [ ]:

# Random Forest
model_rf = RandomForestClassifier(n_estimators=100)
model_rf.fit(X_train_vec,Y_train)

In [ ]:
# Perform K Means 
# 1. Import KMeans from sklearn.cluster
# 2. Create a KMeans object with 3 clusters
# 3. Fit the KMeans object to the data
# 4. Print the cluster centers
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
# Import the data
